### ISSUE TITLE
misspell -v reporting wrong version

### ISSUE THREAD

**Issue by JanneKiiskila** [golangci/misspell#21]
## Expected:
- `misspell` should report the version that was downloaded and taken into use.
- If we download v0.6.0, then expected version is v0.6.0.

## Actual:
```
$ go install github.com/golangci/misspell/cmd/misspell@v0.6.0
go: downloading github.com/golangci/misspell v0.6.0
 11:32 jannek@jannek-P720:~/k8sscripts$ go install github.com/golangci/misspell/cmd/misspell@v0.6.0^C
 11:32 jannek@jannek-P720:~/k8sscripts$ misspell -v
dev
```

**Comment by JanneKiiskila** [comment]
```
$ go version
go version go1.22.3 linux/amd64
```
In case it matters.

**Comment by ldez** [comment]
Hello,

when using `go install` (this is a local build and not a download) the version is `dev` because the way to build doesn't have the arguments to use the git information.
This is expected because it's how `go install` works.

A `go install` of a CLI cannot be compared to Go itself.

You use our [binaries](https://github.com/golangci/misspell/releases) or the [install script](https://github.com/golangci/misspell?tab=readme-ov-file#install).
